config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations'}
  
  root 'static_pages#home'
  get '/pets',    to: 'pets#index'
  # get '/users',   to: 'users#index'
  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/pets/my', to: 'pets#my'
  
  resources :users, :only => [:show, :edit, :update, :destroy]
  resources :pets do
    resources :comments
    member do
      put :encontrei
    end
  end
end

app/models/pet.rb
class Pet
  include Mongoid::Document
  include Mongoid::Timestamps
  
  mount_uploader :image, AvatarUploader
  
  field :name, type: String
  field :breed, type: Breed
  field :status, type: Status
  field :address, type: Address
  field :tag, type: Array
  field :ok, type: Mongoid::Boolean, default: false
  
  belongs_to :user
  embeds_many :tag
  embeds_one :breed
  embeds_one :status
  embeds_one :address
  embeds_many :comments
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.where("ok" => false).all
  end
  
  def my
    @mypets = Pet.where("user" => current_user, "ok" => false).all
  end
  
  def encontrei
    @pet = Pet.where("_id" => params[:id]).first
    @pet.ok = true
    
    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Que ótima noticia! Estamos removendo seu Pet do Catálogo! :)' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
    @user = current_user
  end

  # GET /pets/new
  def new
    @status = StatusModel.all
    @animals = AnimalModel.all
    @breeds = BreedModel.all
    @tags = TagModel.all
    
    @categories = @tags.uniq{|x| x.category}
    
    @pet = Pet.new
    @pet.status=@status.first
  end

  # GET /pets/1/edit
  def edit
    @status = StatusModel.all
    @animals = AnimalModel.all
    @breeds = BreedModel.all
    @tags = TagModel.all
    @address = @pet.address['address']
    
    @categories = @tags.uniq{|x| x.category}
  end

  # POST /pets
  # POST /pets.json
  def create
    @statusPet = StatusModel.where("name" => params[:pet]["status"]).first
    @breedPet = BreedModel.where("_id" => params[:breed]).first
    @addressPet = Address.new("address" => params[:pet]["address"])
    @userPet = current_user._id
    
    @tagPet = []
    tag_ids = params[:tag]
    
    if !tag_ids.nil?
      for t in tag_ids 
        @tagPet.push(TagModel.where("_id" => t).first)
      end
    end
    
    @pet = Pet.new({
      "name" => params[:pet]["name"],
      "status" => @statusPet,
      "breed" => @breedPet,
      "address" => @addressPet,
      "image" => params[:pet]["image"],
      "user_id" => @userPet,
      "ok" => false,
      "tag" => @tagPet
    })
    
    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Seu Pet foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    
    @pet.name = params[:pet]["name"]
    @pet.status = (StatusModel.where("name" => params[:pet]["status"]).first).as_json
    @pet.breed = (BreedModel.where("_id" => params[:breed]).first).as_json
    @pet.address = Address.new("address" => params[:pet]["address"])
    if params[:pet]["ok"].nil?
      @pet.ok = false
    else
      @pet.ok = params[:pet]["ok"]
    end
    
    @tagPet = []
    tag_ids = params[:tag]
    
    if !tag_ids.nil?
      for t in tag_ids 
        @tagPet.push(TagModel.where("_id" => t).first)
      end
      @pet.tag = @tagPet
    end
    
    respond_to do |format|
      if @pet.update
      # if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Seu Pet foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Seu Pet foi removido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id]) or not_found
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :breed, :status, :address, :user, :image, :tag, :ok)
    end
    
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/_comments.html.erb
<div class="commentWrapper">
  <% if @pet.comments.size > 0 %>
    <h2>Comentários</h2>
    <% for comment in @pet.comments %>
      <div class="comment">
         <h4><%= comment.from %> - <%= comment.created_at %></h4>
         <p><%= comment.message %></p>
      </div>
    <% end %>
  <% end %>
</div>
<br />
<div>
  <% if @user %>
    <% if @user._id == @pet.user_id %>
      <%= form_tag encontrei_pet_path(@pet), method: :put do %>
        <%= hidden_field_tag :pet_id, @pet_id%>
        <%= submit_tag 'Encontrei',:class => "btn_main" %>
      <% end %>
    <% else %>
      <h3>Enviar comentário:</h3>
      <%= form_for [@pet, Comment.new] do |f| %>
        <div class="field">
          <%= f.text_field :from, :value => @user['name'], :readonly => true, :disabled => true  %>
          <label for="from">De</label> 
        </div>
        <label for="message">Mensagem</label>
        <div class="field"><%= f.text_area :message, :rows => 10 %></div>
        <%= recaptcha_tags %>
        <p><%= f.submit "Salvar comentário", :class => "submit"%></p>
      <% end %>
    <% end %>
  <% else %>
    <h3>Enviar comentário:</h3>
    <%= form_for [@pet, Comment.new] do |f| %>
      
      <div class='field'>
            <%= f.text_field :from %>
            <label for="from">De</label> 
      </div>
      <div class="field"><%= f.text_area :message, :rows => 10 %></div>
      <%= recaptcha_tags %>
      <p><%= f.submit "Salvar comentário", :class => "submit"%></p>
    <% end %>
  <% end %>
</div>
<br />

app/views/pets/_form.html.erb
<!--Temporario -->
<style>
input[type="checkbox"] {
  display: block;
}
</style>

<%= form_with(model: pet, local: true, :class => 'form full') do |form| %>
  <% if pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <% if @pet.image? %>
    <div class=”thumbnail”>
      <%= image_tag @pet.image, id: "avatar" %>
    </div>
    <% end %>
    <label class="upload_image" for="pet_image">Upload da Imagem <i class="material-icons">cloud_upload</i></label>
    <%= form.file_field :image, id: "pet_image" %>
    <%= form.hidden_field :image_cache %>
  </div>
  <div class="field">
    <% if @pet.persisted? && @pet.image? %>
    <label>
      <%= form.check_box :remove_image %>
    </label>
    <% end %>
  </div>
  <br />

  <div class="field">
    <%= form.text_field :name, id: :pet_name %>
    <label for="pet_name">Nome do pet</label>
  </div>

  <div class="field">
    <% if @pet.breed.nil? %>
      <%= select_tag :animal, options_from_collection_for_select(@animals, "name", "name"), :onchange => "filterBreed(this.value);", :include_blank => "Selecione o tipo de animal" %>
    <% else %>
      <%= select_tag :animal, options_from_collection_for_select(@animals, "name", "name", :selected => @pet.breed['type']['name']), :onchange => "filterBreed(this.value);", :include_blank => "Selecione o tipo de animal"  %>
    <% end %>
  </div>
  
  <div class="field">
      <%= select_tag :breed %>
  </div>
  
  <div class="field">
    <% if @pet.status.nil? %>
      <%= form.select :status, @status.collect { |status| [status.name] } %>
    <% else %>
      <%= form.select :status, @status.collect { |status| [status.name] }, :selected => @pet.status['name'] %>
    <% end %>
  </div>

  <div class="field">
    <% if @pet.address.blank? %>
      <%= form.text_field :address, id: :pet_address, placeholder: "" %>
    <% else %>
      <%= form.text_field :address, :value => @pet.address['address'], id: :pet_address %>
    <% end %>
    <label for="pet_address">Endereço</label>
  </div>
<br />

  <div class="field">
    <% for c in @categories %>
    <div>
      <h3><%= c.categoria.capitalize %></h3>
        <% for tag in @tags %>
          <% if tag.category == c.category %>
            <% if !@pet.name.blank? && @pet.tag.to_json.include?(tag.to_json) %>
              <%= check_box_tag 'tag[]', tag._id, true, id: ActiveSupport::Inflector.transliterate(tag.name.downcase).to_s %>
              <label for= "<%= ActiveSupport::Inflector.transliterate(tag.name.downcase).to_s %>"> <%= tag.name %> </label>
            <% else %>
              <%= check_box_tag 'tag[]', tag._id, nil, id: ActiveSupport::Inflector.transliterate(tag.name.downcase).to_s %>
              <label for= "<%= ActiveSupport::Inflector.transliterate(tag.name.downcase).to_s %>"> <%= tag.name %> </label>
            <% end %>
          <% end %>
        <% end %>
    </div>
    <% end %>
  
  </div>


  <div class="actions">
    <%= form.submit "Salvar Pet", :class => 'submit' %>
  </div>
<% end %>

<script>
  function initialize() {
  
    var input = document.getElementById('pet_address');
    var autocomplete = new google.maps.places.Autocomplete(input);
    
    $(document).ready(function(){
      
      $("#breed").hide();
      $('label[for="pet_breed"]').hide();
    });
    
  
    breed = <%= raw @pet.breed.to_json %>
    if (breed){
      filterBreed(breed.type.name);
      $("#breed").val(breed._id['$oid']);
    }
  };
  
  google.maps.event.addDomListener(window, 'turbolinks:load', initialize);

  function filterBreed(animal){
    
    if(animal){
      breedsFilter = [];
      breeds = <%= raw @breeds.to_json %>;
      
      for (var i in breeds) {
        if (breeds[i].type.name == animal){
          breedsFilter.push(breeds[i]);
        };
      };
      
      if(breedsFilter)
        $(document).ready(function(){
          $("#breed").find('option').remove();
          
          $("#breed").show();
          $('label[for="pet_breed"]').show();
          
          for (var b in breedsFilter){  
            $("#breed").append("<option value='"+breedsFilter[b]._id['$oid']+"'>"+breedsFilter[b].name+"</option>");
          };
          
        });
        
    }else{
      $(document).ready(function(){
        $("#breed").hide();
        $('label[for="pet_breed"]').hide();
      });
    }
    
  };
</script>

app/views/pets/_share.html.erb
<div>
  <% if @pet.status['name'] == "Adoção" %>
    <%= social_share_button_tag("Olá eu sou "+@pet.name+", você me quer me adotar? #LosPets", :url => pet_url, desc: "Olá eu sou "+@pet.name+", você me quer me adotar? #LosPets") %>
  <% elsif @pet.status['name'] == "Resgatado" %>
    <%= social_share_button_tag("Olá eu sou "+@pet.name+", você sabe quem é meu dono? #LosPets", :url => pet_url, desc: "Olá eu sou "+@pet.name+", você sabe quem é meu dono? #LosPets") %>
  <% else %>
    <%= social_share_button_tag("Olá eu sou "+@pet.name+", você me viu por ai? #LosPets", :url => pet_url, desc: "Olá eu sou "+@pet.name+", você me viu por ai? #LosPets") %>
  <% end %>
</div>

app/views/pets/edit.html.erb
<% provide(:title, "Pet") %>
<% if current_user == @pet.user %>
    <h1>Editando perfil do Pet</h1>
    
    <%= render 'form', pet: @pet %>
    
    <div class="petActions">
        <%= link_to 'Perfil', @pet, :class => "btn2" %>
        <%= link_to 'Deletar Pet', @pet, method: :delete, :class => "btn_remove", data: { confirm: 'Você tem certeza que deseja excluir este Pet?' } %>
        <%= link_to 'Voltar', pets_path, :class => "btn2" %>
    </div>
<% else %>  
    <h2>Acesso Negado!</h2>
    <small>Se você estiver com problemas de acesso entre em contato com o administrador do sistema!</small>
    <br />
    <div class="petActions">
        <%= link_to 'Voltar', @pet, :class => "btn2"  %>
    </div>
<% end %>

app/views/pets/index.html.erb
<% provide(:title, "Pet") %>
<div class="petList">
  <div class="titleWrapper">
    <h1>Pets</h1>
    <%= form_with(local: true, :class => 'form withinTitle') do |form| %>
      <div class="field">
        <%= form.text_field :pet_search, id: :pet_search %>
        <label for="pet_search">Pesquisar por pet</label>
      </div>
    <% end %>
  </div>
  

  <% @pets.each do |pet| %>
    <div class="pet">
      <div class="petName"><%= pet.name %></div>
      <div class="petWrapper">
        <div class="petImage"><%= image_tag(pet.image, class:"pet_image_small") %></div>
        <div class="petDescriptor">
          
          
          <div class="petBreed">
            <span>Raça:</span>
            <%= pet.breed['name'] %> - <%= pet.breed['type']['name']%>
          </div>
          
          <div class="petStatus">
            <span>Status:</span>
            <%= pet.status['name'] %>
            </div>
            
          <div class="petAddress">
            <span>Endereço:</span>
            <%= pet.address['address'] %>
          </div>
          
          <div class="petOwner">
            <span> Usuário/Tutor:</span>
            <% if pet.user.present? %>
            <%= pet.user['name'] %>
            <% else %>
            Usuário inexistente!
            <% end %>
          </div>
          
          <div class="petCharacteristics">
            <span>Características</span>
            <% pet.tag.each do |tag| %>
              <%= tag.name %>
            <% end %>
          </div>
          
        </div>        
        <div class="petActions"><%= link_to 'Ver Detalhes', pet %></div>  
      </div>
      
    </div>
  <% end %>
</div>

<script>
  $(document).ready(function(){
  $("#pet_search").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $(".pet").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>

app/views/pets/my.html.erb
<% provide(:title, "Pet") %>

<% if current_user.present? %>
  <h1>Meus Pets</h1>
  
  <% @mypets.each do |pet| %>
    <div class="pet">
      <div class="petName"><%= pet.name %></div>
      <div class="petWrapper">
        <div class="petImage"><%= image_tag(pet.image, class:"pet_image_small") %></div>
        <div class="petDescriptor">
          
          <div class="petBreed">
            <span>Raça:</span>
            <%= pet.breed['name'] %>
          </div>
          
          <div class="petStatus">
            <span>Status:</span>
            <%= pet.status['name'] %>
            </div>
            
          <div class="petAddress">
            <span>Endereço:</span>
            <%= pet.address['address'] %>
          </div>
          
          <div class="petOwner">
            <span> Usuário/Tutor:</span>
            <% if pet.user.present? %>
            <%= pet.user['name'] %>
            <% else %>
            Usuário inexistente!
            <% end %>
          </div>
          
          <div class="petCharacteristics">
            <span>Características</span>
            <% pet.tag.each do |tag| %>
              <%= tag.name %>
            <% end %>
          </div>
          
        </div>        
        <div class="petActions">
          <%= link_to 'Ver Detalhes', pet %>
          <%= link_to 'Editar perfil', edit_pet_path(pet), :class => "btn2" %>
          <%= link_to 'Deletar Pet', pet, method: :delete, :class => "btn_remove", data: { confirm: 'Você tem certeza que deseja excluir este Pet?' } %>
        </div>  
      </div>
      
    </div>
  
  <% end %>
  <div class="linkwrapper">
    <%= link_to 'Cadastrar novo pet', new_pet_path, :class => "btn_main" %>
  </div>
  
<% else %>
  <script type="text/javascript">
    window.location.href="/users/sign_up"
  </script>
<% end %>

app/views/pets/new.html.erb
<% provide(:title, "Pet") %>
<h1>Novo Pet</h1>

<%= render 'form', pet: @pet %>

<div class="petActions">
    <%= link_to 'Voltar', pets_path, :class => "btn2" %>
</div>

app/views/pets/show.html.erb
<% provide(:title, "Pet") %>

<div class="petProfile">

  <div class="petImage">
    <%= image_tag(@pet.image, class:"pet_image") %>    
  </div>
  
  <div class="petDescription">
    <p>
      <strong>Nome do pet:</strong>
      <%= @pet.name %>
    </p>
    
    <p>
      <strong>Raça:</strong>
      <%= @pet.breed['name'] %>
    </p>
    
    <p>
      <strong>Status:</strong>
      <%= @pet.status['name'] %>
    </p>
    
    <p>
      <strong>Endereço:</strong>
      <%= @pet.address['address'] %>
    </p>
    
    <p>
      <strong>Usuário/Tutor:</strong>
      <% if @pet.user.present? %>
        <% if @pet.user.avatar.present? %>
          <%= image_tag(@pet.user.avatar, class: "user_image", style: "width:45px;height:45px") %>
        <% else %>
           <%= image_tag("users/Paw-icon.png", class:"user_image", style:"width:45px;height:45px") %>
         <% end %>
        <%= @pet.user['name'] %>
      <% else %>
        Usuário inexistente!
      <% end %>
    </p>
    
    <p>
      <strong>Características:</strong>
      <% @pet.tag.each do |tag| %>
        <%= tag.name %><br />
      <% end %>
    </p>
  </div>

  <% if !@pet.address['coordinates'].nil? %>
    <div>
      <img src="https://maps.googleapis.com/maps/api/staticmap?center=<%= @pet.address['coordinates'][1] %>,<%= @pet.address['coordinates'][0] %>&zoom=13&size=600x300&maptype=roadmap&markers=<%= @pet.address['coordinates'][1] %>,<%= @pet.address['coordinates'][0] %>&key=AIzaSyDMI_uP_6ASCcL8ETf3uTu2_8hy1hn1ROw" class="static_map"></img>
    </div>
  <% end %>
  
<%= render 'pets/comments' %>
<%= render 'pets/share' %>

  <div class="petActions">
    <% if @pet.user == current_user %>
      <%= link_to 'Editar perfil', edit_pet_path(@pet), :class => "btn2" %>
    <% end %>
    <%= link_to 'Voltar', pets_path, :class => "btn2" %>
  </div>
</div>